# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"stats": "00_core.ipynb",
         "log_softmax": "00_core.ipynb",
         "accuracy": "00_core.ipynb",
         "error": "00_core.ipynb",
         "nll": "00_core.ipynb",
         "plotdist": "00_core.ipynb",
         "df_meminfo": "02_pandas.ipynb",
         "mem_usage": "02_pandas.ipynb"}

modules = ["core.py",
           "pandas.py"]

doc_url = "https://kdorichev.github.io/deeplearning/"

git_url = "https://github.com/kdorichev/deeplearning/tree/master/"

def custom_doc_links(name): return None