#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"stats": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/kdorichev/deeplearning/tree/master/"

def custom_doc_links(name): return None