#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['stats', 'log_softmax']

#Cell
def stats(x):
    "Returns `mean` and `std` of a tensor"
    return x.mean(),x.std()

#Cell
def log_softmax(x):
    return x - x.exp().sum(-1).log().unsqueeze(-1)